spring:
  config:
    import:
      - classpath:application-logging.yaml
      - classpath:application-db.yaml
      - classpath:application-springdoc.yaml
      - classpath:application-security.yaml
  application:
    name: sample-user-api
  main:
    banner-mode: off

server:
  port: ${SERVER_PORT:8083}
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

