logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","thread":"%t","logger":"%c","message":"%m"}\n'
  level:
    org.labcabrera: ${LOG_LEVEL:DEBUG} 
    org.apache.kafka: ${KAFKA_LOG_LEVEL:WARN}
    org.springframework.cloud.stream: WARN
    org.springframework.cloud.function: WARN
    org.springframework.kafka: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    root: INFO