apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: archetype-spring-cloud-stream-vertical-slice-cert
spec:
  secretName: archetype-spring-cloud-stream-vertical-slice-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: sample-root-ca
    kind: ClusterIssuer
  commonName: archetype-spring-cloud-stream-vertical-slice.local
  dnsNames:
    - archetype-spring-cloud-stream-vertical-slice.local