apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-users-api
spec:
  secretName: sample-users-api-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: template-root-ca
    kind: ClusterIssuer
  commonName: sample-users-api.local
  dnsNames:
    - sample-users-api.local