apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cert.yaml
  - configmap.yaml
  - secret.yaml
# ConfigMap and Secret provided as manifest files: configmap.yaml, secret.yaml
